# Title - telecom churn eda cleaning

**Predicting customer churn for a telecom company using
** historical customer data to identify at-risk customers
** and reduce churn rate.

# Importing Libraries

In [1]:
import pandas as pd
import numpy as np

# Loading the Dataset

In [2]:
df = pd.read_csv("Telco-Customer-Churn.csv")

In [3]:
# check top rows
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
# check information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [5]:
# check shape
df.shape

(7043, 21)

In [6]:
# check size
df.size

147903

In [7]:
# check columns
df.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

# Correct column names

In [8]:
df.columns = df.columns.str.lower()

In [9]:
df = df.rename(columns={
    "customerid" : "customer_id",
    "seniorcitizen": "senior_citizen",
    "monthlycharges": "monthly_charges",
    "totalcharges": "total_charges",
    "phoneservice": "phone_service",
    "internetservice": "internet_service",
    "onlinesecurity": "online_security",
    "onlinebackup": "online_backup",
    "deviceprotection": "device_protection",
    "techsupport": "tech_support",
    "streamingtv": "streaming_tv",
    "streamingmovies": "streaming_movies",
    "paperlessbilling": "paperless_billing",
    "paymentmethod": "payment_method",
    "multiplelines": "multiple_lines",
})

In [10]:
print(df.columns.tolist())

['customer_id', 'gender', 'senior_citizen', 'partner', 'dependents', 'tenure', 'phone_service', 'multiple_lines', 'internet_service', 'online_security', 'online_backup', 'device_protection', 'tech_support', 'streaming_tv', 'streaming_movies', 'contract', 'paperless_billing', 'payment_method', 'monthly_charges', 'total_charges', 'churn']

# Missing values check

In [11]:
df.isnull().sum()

customer_id          0
gender               0
senior_citizen       0
partner              0
dependents           0
tenure               0
phone_service        0
multiple_lines       0
internet_service     0
online_security      0
online_backup        0
device_protection    0
tech_support         0
streaming_tv         0
streaming_movies     0
contract             0
paperless_billing    0
payment_method       0
monthly_charges      0
total_charges        0
churn                0
dtype: int64

# Correct data type

In [12]:
# check data types
df.dtypes

customer_id              str
gender                   str
senior_citizen         int64
partner                  str
dependents               str
tenure                 int64
phone_service            str
multiple_lines           str
internet_service         str
online_security          str
online_backup            str
device_protection        str
tech_support             str
streaming_tv             str
streaming_movies         str
contract                 str
paperless_billing        str
payment_method           str
monthly_charges      float64
total_charges            str
churn                    str
dtype: object

In [13]:
# correct total_chargers column
df["total_charges"] = pd.to_numeric(df["total_charges"], errors="coerce")

# Again check missing values

In [14]:
# total_charges column check
df["total_charges"].isnull().sum()

np.int64(11)

In [15]:
df[df["total_charges"].isnull()][["tenure", "total_charges"]]

      tenure  total_charges
488        0            NaN
753        0            NaN
936        0            NaN
1082       0            NaN
1340       0            NaN
3331       0            NaN
3826       0            NaN
4380       0            NaN
5218       0            NaN
6670       0            NaN
6754       0            NaN

**tenure column dikhakar hum confirm kar rahe h: 
** jitni bhi NaN rows hain, sab mein tenure = 0 hai 
** matlab reason ye hi hai, koi data error nahi hai."

**In rows mein tenure=0 hai (naye customers), total_charges ko 0 se fill kar sakte hain

In [16]:
df["total_charges"] = df["total_charges"].fillna(0)

# make senior citizen column readble

In [17]:
df["senior_citizen"] = df["senior_citizen"].map({0: "No", 1: "Yes"})

# check duplicate

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
df["customer_id"].duplicated().sum()

np.int64(0)

# Feature Engineering (New columns)

In [20]:
# tenure_group
bins = [0, 12, 24, 48, 60, np.inf]
labels = ["0-12", "13-24", "25-48", "49-60", "60+"]
df["tenure_group"] = pd.cut(df["tenure"], bins=bins, labels=labels, right=True, include_lowest=True)

In [21]:
# avg_monthly_spend
df["avg_monthly_spend"] = np.where(
    df["tenure"] > 0,
    df["total_charges"] / df["tenure"],
    df["monthly_charges"] 
)

In [22]:
# num_services
service_cols = [
    "phone_service", "internet_service", "online_security", "online_backup",
    "device_protection", "tech_support", "streaming_tv", "streaming_movies"
]
df["num_services"] = df[service_cols].apply(
    lambda row: sum(row == "Yes"), axis=1
)

In [23]:
# is_new_customer
df["is_new_customer"] = df["tenure"] < 6

In [24]:
df.head()

,customer_id,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,internet_service,online_security,...,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn,tenure_group,avg_monthly_spend,num_services,is_new_customer
0,7590-VHVEG,Female,No,Yes,No,1,No,No phone service,DSL,No,...,Month-to-month,Yes,Electronic check,29.85,29.85,No,0-12,29.850000,1,True
1,5575-GNVDE,Male,No,No,No,34,Yes,No,DSL,Yes,...,One year,No,Mailed check,56.95,1889.50,No,25-48,55.573529,3,False
2,3668-QPYBK,Male,No,No,No,2,Yes,No,DSL,Yes,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,0-12,54.075000,3,True
3,7795-CFOCW,Male,No,No,No,45,No,No phone service,DSL,Yes,...,One year,No,Bank transfer (automatic),42.30,1840.75,No,25-48,40.905556,3,False
4,9237-HQITU,Female,No,No,No,2,Yes,No,Fiber optic,No,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0-12,75.825000,1,True

In [25]:
df.shape

(7043, 25)

# Data cleaned Sucessfully

# Connect to MS SQL Server

In [26]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

# SQL Server connection
host = r"DESKTOP-N9K70SP\SQLEXPRESS"
database = "telecomChurnDB"

# ODBC Driver
driver = quote_plus("ODBC Driver 17 for SQL Server")

# Create SQL Server connection
engine = create_engine(
    f"mssql+pyodbc://@{host}/{database}"
    f"?driver={driver}&trusted_connection=yes"
)

# Write DataFrame to SQL Server
df.to_sql(
    "Telco-Customer-Churn",
    engine,
    if_exists="replace",
    index=False
)

# Read back sample
result = pd.read_sql(
    "SELECT TOP 5 * FROM [Telco-Customer-Churn]",
    engine
)

result

,customer_id,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,internet_service,online_security,...,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn,tenure_group,avg_monthly_spend,num_services,is_new_customer
0,7590-VHVEG,Female,No,Yes,No,1,No,No phone service,DSL,No,...,Month-to-month,Yes,Electronic check,29.85,29.85,No,0-12,29.850000,1,True
1,5575-GNVDE,Male,No,No,No,34,Yes,No,DSL,Yes,...,One year,No,Mailed check,56.95,1889.50,No,25-48,55.573529,3,False
2,3668-QPYBK,Male,No,No,No,2,Yes,No,DSL,Yes,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,0-12,54.075000,3,True
3,7795-CFOCW,Male,No,No,No,45,No,No phone service,DSL,Yes,...,One year,No,Bank transfer (automatic),42.30,1840.75,No,25-48,40.905556,3,False
4,9237-HQITU,Female,No,No,No,2,Yes,No,Fiber optic,No,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0-12,75.825000,1,True